version: '3.8'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: energydb
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  usage-service:
    build: ./usage-service
    container_name: usage-service
    depends_on:
      - rabbitmq
      - postgres
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/energydb
      SPRING_DATASOURCE_USERNAME: energy
      SPRING_DATASOURCE_PASSWORD: secret

  percentage-service:
    build: ./percentage-service
    container_name: percentage-service
    depends_on:
      - rabbitmq
      - postgres
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/energydb
      SPRING_DATASOURCE_USERNAME: energy
      SPRING_DATASOURCE_PASSWORD: secret

volumes:
  pgdata: